// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:pocketllm_lite/features/chat/domain/models/chat_message.dart';
import 'package:pocketllm_lite/features/chat/domain/models/chat_persona.dart';
import 'package:pocketllm_lite/features/chat/domain/models/chat_session.dart';
import 'package:pocketllm_lite/features/chat/domain/models/system_prompt.dart';
import 'package:pocketllm_lite/features/chat/domain/models/text_file_attachment.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatMessageAdapter());
    registerAdapter(ChatPersonaAdapter());
    registerAdapter(ChatSessionAdapter());
    registerAdapter(SystemPromptAdapter());
    registerAdapter(TextFileAttachmentAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatMessageAdapter());
    registerAdapter(ChatPersonaAdapter());
    registerAdapter(ChatSessionAdapter());
    registerAdapter(SystemPromptAdapter());
    registerAdapter(TextFileAttachmentAdapter());
  }
}
